name: TESTING
on:
  workflow_dispatch:
    inputs:
      env_source:
        description: Source environment name. Accepted values [dev, qa, preprod]
        required: false
  push:
    branches:
     - main
     - debug

env:
  lol: ${{ (github.event.inputs.env_source != '' && github.event.inputs.env_source) || (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'dev') }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ env.lol }}

    steps:
      - name: Run a multi-line script
#         if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: |
          echo THE TEST
          echo '----------------------------'
          echo ${{ env.lol }}












# name: TESTING
# on:
#   workflow_dispatch:
#     inputs:
#       env_source:
#         description: Source environment name. Accepted values [dev, qa, preprod]
#         required: false
#   push:
#     branches:
#      - main
#      - debug

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     env:
#       DEFINED_ENVIRONMENT: ${{ (github.event.inputs.env_source != '' && github.event.inputs.env_source) || (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'dev') }}
#     environment: ${{ (github.event.inputs.env_source != '' && github.event.inputs.env_source) || (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'dev') }}

#     steps:
#       - name: Run a multi-line script
# #         if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
#         run: |
#           echo THE TEST
#           echo ${{ env.DEFINED_ENVIRONMENT }}
